NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
my_array = np.arange(0,11)

In [3]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
my_array[4]

4

In [7]:
my_array[1:5]
#Slice Notation

array([1, 2, 3, 4])

In [8]:
my_array[0:5] = 100

In [9]:
my_array

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [31]:
my_array_2d = np.array([[5,10,15,18],[20,25,30,33],[35,40,45,48],[50,55,60,63],[65,70,75,78]])

In [32]:
my_array_2d

array([[ 5, 10, 15, 18],
       [20, 25, 30, 33],
       [35, 40, 45, 48],
       [50, 55, 60, 63],
       [65, 70, 75, 78]])

In [40]:
my_array_2d[2:4,1:3]
#2D Array Slicing

array([[40, 45],
       [55, 60]])

In [41]:
arr = np.arange(1,11)

In [42]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
bool_arr = arr > 5

In [45]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [46]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [49]:
arr[arr < 3]


array([1, 2])

In [50]:
my_array_2d[my_array_2d > 35]

array([40, 45, 48, 50, 55, 60, 63, 65, 70, 75, 78])

In [51]:
arr_2d = np.arange(50).reshape(10,5)

In [52]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [53]:
arr_2d[3:7, 1:5]

array([[16, 17, 18, 19],
       [21, 22, 23, 24],
       [26, 27, 28, 29],
       [31, 32, 33, 34]])