In [42]:
print("Hello and Welcome")

Hello and Welcome


In [1]:
my_list = [1, 2, 3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [5]:
my_array = np.array(my_list)

In [6]:
my_array

array([1, 2, 3])

In [7]:
my_matrice = [[1,2,3], [4,5,6], [7,8,9]]

In [8]:
np.array(my_matrice)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5)

array([0.13490981, 0.94428744, 0.44574969, 0.76805472, 0.88153933])

In [17]:
np.random.rand(5,5)

array([[0.57711611, 0.9476173 , 0.66782764, 0.85184713, 0.72151787],
       [0.38646402, 0.13401166, 0.92763154, 0.31484887, 0.62225959],
       [0.17968986, 0.08726238, 0.58594769, 0.41945234, 0.73588432],
       [0.32479612, 0.73047801, 0.23333143, 0.60011514, 0.83389251],
       [0.45845069, 0.71098522, 0.14179064, 0.67476031, 0.16227023]])

In [19]:
np.random.randn(2,4)

array([[ 1.77059337,  0.65016184,  0.53087471, -0.57101612],
       [-0.21695434,  0.1109228 ,  0.5139593 , -0.70485546]])

In [21]:
np.random.randint(1,100, 10)

array([15, 98, 18, 94, 64,  6, 87, 31, 80, 41])

In [26]:
arr = np.arange(10)

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
random_arr = np.random.randint(0, 50, 10)

In [31]:
random_arr

array([37, 12,  5, 29, 40, 38, 35, 40, 15, 13])

In [33]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [38]:
random_arr.argmax()

'Returns the index location of the maximum value'

In [40]:
arr.shape

(10,)

In [41]:
arr.dtype

dtype('int32')