NumPy Operations
- Array with Array
- Array with Scalars
- Universal Array Functions

In [1]:
import numpy as np

In [3]:
my_array = np.arange(0,11)

In [4]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
my_array * my_array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [9]:
my_array * 5
#With scalar operation

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [11]:
my_array / my_array

<ipython-input-11-18596061bb4f>:1: RuntimeWarning: invalid value encountered in true_divide
  my_array / my_array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [12]:
my_array ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [13]:
np.sqrt(my_array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [14]:
np.exp(my_array)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [15]:
np.sin(my_array)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [16]:
np.log(my_array)

<ipython-input-16-53bc6e9f5089>:1: RuntimeWarning: divide by zero encountered in log
  np.log(my_array)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [17]:
np.deg2rad(my_array)

array([0.        , 0.01745329, 0.03490659, 0.05235988, 0.06981317,
       0.08726646, 0.10471976, 0.12217305, 0.13962634, 0.15707963,
       0.17453293])